# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BangazonAPI', '0002_paymenttype'),
        ('BangazonAPI', '0002_product'),
    ]

    operations = [
    ]
